### ISSUE TITLE
Prepare more lessons

### ISSUE THREAD

**Issue by xxthunder** [avengineers/hello-unit-testing#4]
For demonstration of unit testing of embedded C using GoogleTest we definitely need more practical examples, e.g.,:

- filter
- monitoring
- state machine
- ...

The examples shall show how to use GTest and GMock (mocks created by hammocking) in an SPL in different scenarios:

- call by value
- call by reference
- pointer arguments
- ...

**Comment by xxthunder** [comment]
Now we can start with more realistic examples.

**Comment by WhiteSpirit329** [comment]
Due to last minute change, I added additional example 1.5 before lesson 2 on the [4-prepare-lesson-3-advanced](https://github.com/avengineers/hello-unit-testing/tree/4-prepare-lesson-3-advanced) branch. Locally all tests are running. Tags are moved to correct places in the new branch. Currently only HEAD and develop points to the branch without example 1.5.

**Comment by xxthunder** [comment]
I think we prepared a lot. Refactoring maybe later.
